interviewapp/users/models.py
from interviewapp import db
from interviewapp import flask_bcrypt
from sqlalchemy.ext.hybrid import hybrid_property



class User(db.Model):
    __tablename__ = "user"
    __table_args__ = {"extend_existing": True}

    # The primary key for each record
    id = db.Column(db.Integer, primary_key=True)

    # The unique username for user
    username = db.Column(db.String(50), unique=True, nullable=False)

    # The unique emai for  user
    email = db.Column(db.String(100), unique=True, nullable=False)

    # The hashed password for the user
    _password = db.Column(db.String(60), unique=True, nullable=True)

    is_admin = db.Column(db.Boolean, default=False)
    
    is_recruiter = db.Column(db.Boolean, default=False)

    is_specialist = db.Column(db.Boolean, default=False)


    def __init__(self,username, email, password):
        self.username = username
        self.email = email
        self.password = password

    def __repr__(self):
        return "{0}".format(self.username)

    @hybrid_property
    def password(self):
        return self._password
    
    @password.setter
    def password(self,password):
        self._password = flask_bcrypt.generate_password_hash(password)

    def get_id(self):
        return self.id 

    def is_anonymous(self):
        return False 

    def is_authenticated(self):
        return True 

    def is_active(self):
        return True
        
    @classmethod
    def create_user(cls, username, email, password):
        user = User(username, email, password)
        return user

    @classmethod
    def create_super_user(cls,username, email, password):
        user = cls.create_user(username, email, password)
        user.is_admin = True 
        return user 

    

interviewapp/users/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField, EmailField, RadioField, PasswordField, BooleanField
from wtforms.validators import DataRequired, InputRequired, Length
from sqlalchemy import exc
from flask import current_app
from interviewapp import db
from interviewapp.users.models import User
from password_generator import PasswordGenerator



class AddUserForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    email = EmailField("Email", validators=[DataRequired()])
    is_expert = BooleanField("expert")
    is_recruiter = BooleanField("recruiter")
    password = PasswordField()
    submit = SubmitField("Submit")


    def save(self):
        user = User(
            username=self.username.data, 
            email=self.email.data,
            password=self.password.data
        )

        if self.is_expert.data and self.is_recruiter.data:
            user.is_recruiter = True 
            user.is_specialist = True

        else:
            if self.is_recruiter.data:
                user.is_recruiter = True 

            if self.is_expert.data:
                user.is_specialist = True

        return user
       
            
           
class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=6)])
    submit = SubmitField("Sign in")

interviewapp/users/views.py
from ast import match_case
from crypt import methods
from flask import (
    Blueprint, redirect, 
    request, url_for, 
    render_template, flash, render_template_string, current_app
    )

from flask_login import login_required, login_user, logout_user,current_user
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy import exc
from interviewapp.users.forms import AddUserForm, LoginForm
from interviewapp.users.models import User
from interviewapp import flask_bcrypt, db
import smtplib
from decouple import config as environ
from email.message import EmailMessage

users = Blueprint('users', __name__)

@users.route("/")
@login_required
def listing():
    page_title = "users"
    users = User.query.all()
    count = len(users)
    return render_template('users/user_list.html',page_title=page_title,users=users,count=count)

@users.route('/add/', methods=['GET', 'POST'])
@login_required
def add():
    page_title = "new user"
    # new user form
    form = AddUserForm()
    # on POST request
    if request.method == 'POST':
        if form.validate_on_submit():
            # PasswordGenerator module to generate a password for each user
            from password_generator import PasswordGenerator
            pwo = PasswordGenerator()
            # set generated password max lenght characteres to be 8
            pwo.maxlen = 8
            # saving generated password
            password = pwo.generate()
            # setting generated password
            form.password.data = password
            # create user instance
            user = form.save()
            try:
                db.session.add(user)
                db.session.commit()
                 # sending email to the new user
           
                message = EmailMessage()
                # fetching email address from environment variable
                sender = environ('EMAIL_ADDRESS')
                recipient = form.email.data 
                username = form.username.data

                # handle mail sending proccess
                try:
                    message['Subject'] = 'Registration Interview.com'
                    message['From'] = sender 
                    message['To'] = form.email.data 
                    message.set_content('registered on interview')
                    message.add_alternative(
                    """
                    <p>Hello {0},</p>
                    <p>Here are your login and password on <a href='#' style='text-decoration:none'>Interview.com</a></p>
                    <p>Login: {1} <br> Password: {2}</p> 
                    """.format(username,recipient,password), subtype='html')
                    server = smtplib.SMTP('smtp.gmail.com',587)
                    server.starttls()
                    server.login(sender,environ('EMAIL_PASSWORD'))
                    server.send_message(message)
                    flash("user created and email sent to {0}".format(recipient), 'success')
                    return redirect(url_for('users.listing'))
                except smtplib.SMTPException as e:
                    # log the error
                    current_app.log_exception("Mail could not be sent to user")
                    flash('Error: unable to send email','warning')
                    return render_template("users/user_add.html", form=form,page_title=page_title)
            
            except exc.IntegrityError as e:
                # log the error here
                return render_template("users/user_add.html", form=form,page_title=page_title)
            except exc.SQLAlchemyError:
                # log the error here
                flash("Something wrnt wrong when creating this user !")
                return render_template("users/user_add.html", form=form,page_title=page_title)

        # when user send invalid data
        else:
            flash("Invalid data", 'warning')
    # on GET request
    return render_template(
        "users/user_add.html", 
        form=form,
        page_title=page_title
    )

@users.route("/search/", methods=['GET','POST'])
@login_required
def search():
    page_title = 'Search'
    user_list = User.query.all()
    # count present user into the database
    count = len(user_list)
    # user submit data on post method request
    if request.method == 'POST':
        users = User.query 
        query = request.form.get('search')
        # when user send empty string
        if not query:
            flash("warning: empty query was sent",'warning')
            # redirect user to interview list page
            return redirect(url_for('users.listing'))
        
        # user string is not empty
        page_title  = "{0} result".format(query)
        matching = users.filter(User.username.like("%" + query + "%")).all()
        
        # user query matches some data in the database
        if len(matching) > 0:
            # set user list to those matching the query
            user_list = matching 
            # count how many user match the query
            count = len(user_list)
        
        # matching length less than 0 nothing match user query
        else:
            flash('{0} does not match any user'.format(query),'info')
            return redirect(url_for('users.listing'))

    # GET request
    return render_template(
        'users/user_list.html',
         page_title=page_title,
         users=user_list,count=count
    )

@users.route('/filter/',methods=['GET','POST'])
def filter():
    page_title = 'users'
    users = User.query.all()
    count = len(users)
    matching = []
    if request.method == 'POST':
        role = request.form.get('role')
        if not role:
            return redirect(url_for('users.listing'))

        if role == 'expert':
            matching = User.query.filter_by(is_specialist=True).all()
            
        elif role == 'recruiter':
            matching = User.query.filter_by(is_recruiter=True).all()
            
        elif role == 'admin':
            matching = User.query.filter_by(is_admin=True).all()
        
        if len(matching) > 0:
            users = matching
            count = len(users)

    return render_template(
        'users/user_list.html',
        page_title=page_title,
        users=users,
        count=count
    )

        


@users.route('/delete/<id>/', methods=["GET", "POST"])
def delete(id):
    page_title ="Delete user"
    user_id = id
    user = None
    try:
        user = User.query.filter_by(id=user_id).one()
    except exc.NoResultFound:
        flash("User with {id} id does not exist".format(user_id),'danger')
        return redirect(url_for('users.delete'))

    if request.method == "POST":
        if not user == None:
            try:
                db.session.delete(user)
                db.session.commit()
                flash("{} deleted".format(user.email), 'info')
                return redirect(url_for('users.listing'))
            except exc.SQLAlchemyError:
                flash("Error: user could be deleted", 'warning')
    return render_template('users/user_delete.html',page_title=page_title,user=user)

@users.route('/login/', methods=['GET',"POST"])
def login():
    page_title = "Login"
    if current_user.is_authenticated:
        return redirect(url_for('interviews.home'))

    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()

            if not user:
                flash('No such user exsts','warning')
                return render_template('users/login.html',form=form, page_title=page_title)

            if(not flask_bcrypt.check_password_hash(user.password,form.password.data)):
                flash("Invalid password.", 'warning')
                return render_template('users/login.html', form=form, page_title=page_title)

            login_user(user)
            flash('Success!', 'success')
            return redirect(url_for('interviews.home'))
    return render_template('users/login.html', page_title = page_title, form=form)


@users.route('/logout/', methods=["GET"])
def logout():
    logout_user()
    return redirect(url_for('users.login'))
     

interviewapp/templates/users/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container ">
  <div class="col-md-10">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
  <div class="col-lg-4 container col-md-6 mt-5">
      <form method="POST" action="">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="mb-4 text-center text-secondary">Sing in to Interview.com</legend>
          </fieldset>
          <div class="form-group mb-3">
              {{ form.email.label(class="form-control-label text-secondary")}}
              {% if form.email.errors %}
                  {{ form.email(class="form-control is-invalid")}}
                  <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                      <small class="text-danger">{{error}}</small>
                      {% endfor %}
                  </div>
              {% else %}
                {{ form.email(class="form-control")}}
              {% endif %}
          </div>
          <div class="form-group mb-3">
              {{ form.password.label(class="form-control-label text-secondary")}}
              {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid")}} 
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                      <small class="text-danger">{{error}}</small>
                    {% endfor %}
                </div>
              {% else %}
                  {{ form.password(class="form-control")}}
              {% endif %}
          </div>
          {{ form.submit(class="btn btn-success  mt-2 col-12")}}
          </fieldset>
      </form>
    </div>
</div>
{% endblock %}

interviewapp/templates/users/search_result.html
{% extends 'base.html' %}
{% block content %}

<div class="container col-lg-10">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
        {% endif %}
    {% endwith %}

    {% if users %}
        <div class="d-flex justify-content-center mb-2">
            <form method='GET' action="{{ url_for('users.search') }}" class="col-lg-8" style="background:gainsboro;border:none" id="searchForm" >
               <small>Search by</small>
                <select class="mb-2">
                    <option>Expert</option>
                    <option>Recruiter</option>
                    <option>Admin</option>
                </select>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name='search' placeholder="search..." aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            <a href="{{ url_for('users.add') }}">
                <i class="fa fa-plus-circle text-success" aria-hidden="true" style='font-size:30px'></i>
            </a>
        </div>
        <table class="table table-striped bg-white">
            <thead class="bg-success text-white">
            <tr>
                <th>USERNAME</th>
                <th>EMAIL ADDRESS</th>
                <th>RECRUITER</th>
                <th>EXPERT</th>
                <th>ADMIN</th>
                <th>DELETE</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
            <tr>
                <td>
                    <input type='checkbox' class="ms-1" value='{{ user.id }}'>
                    <a href="#" class=" text-success">{{ user.username | title}}</a>
                </td>
                <td>
                    <a href="#" class="nav-link text-success">{{ user.email | title}}</a>
                </td>
                <td>
                    {% if user.is_recruiter %}
                    <i class="fa fa-check text-success" style="font-size:17px"></i>
                    {% else %}
                    <i class="fa fa-close text-danger" style="font-size:17px"></i>
                    {% endif %}
                </td>
                <td>
                    {% if user.is_specialist %}
                    <i class="fa fa-check text-success" style="font-size:17px"></i>
                    {% else %}
                    <i class="fa fa-close text-danger" style="font-size:17px"></i>
                    {% endif %}
                </td>
                <td>
                    {% if user.is_admin %}
                    <i class="fa fa-check text-success" style="font-size:17px"></i>
                    {% else %}
                    <i class="fa fa-close text-danger" style="font-size:17px"></i>
                    {% endif %}
                </td>
                <td style="text-align:center">
                    <a href="{{ url_for('users.delete', id=user.id) }}">
                       <i class="fa fa-trash text-warning" aria-hidden="true" style='font-size:20px'></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="container">
           <h2>No users into the database</h2>
        </div>
    {% endif %}
   </div>
{% endblock %}

interviewapp/templates/users/user_add.html
{% extends 'base.html' %}
{% block content %}
<style>
    ul li{list-style:none;}
    ul{padding:0px}
</style>
<div class="container col-lg-4">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
        {% endif %}
    {% endwith %}
    <form method="POST" class="mt-4">
        <h3 class="text-muted text-center">New user</h3>
        {{ form.hidden_tag()}}
        <div class="form-group">
            {{form.username.label(class="form-control-label text-muted")}}
            {{ form.username(class="form-control")}}
        </div>
        <div class="form-group mt-3">
            {{form.email.label(class="form-control-label text-muted")}}
            {{ form.email(class="form-control")}}
        </div>
        <div class="form-group mt-3">
            {{ form.is_recruiter(class="")}}
            {{ form.is_recruiter.label(class="form-control-label text-muted")}}
        </div>
        <div class="form-group mt-2">
            {{ form.is_expert(class='')}}
            {{ form.is_expert.label(class='form-control-label text-muted')}}
        </div>
        {{ form.submit(class="btn btn-success mt-3 col-md-12")}}
    </form>
</div>
{% endblock %}

interviewapp/templates/users/user_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <p> Do you really want to delete 
        {% if user.username %}
        <b>{{ user.username }}</b> ?
        {% else %}
        <b>{{ user.email }}</b> ?
        {% endif %}
    </p>
    <form method="POST" action="" style="background:none;border:none">
        <div class="group-form">
            <a href="{{ url_for('users.listing') }}" class="btn btn-secondary btn-sm">Cancel</a>
            <input type="submit" value="delete" class="btn btn-danger btn-sm">
        </div>
    </form>
</div>
{% endblock %}

interviewapp/templates/users/user_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container col-lg-10">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
        {% endif %}
    {% endwith %}

    {% if users %}
        <div class=" mb-2 mt-3">
            <form method='POST' action="{{ url_for('users.search') }}" class="col-lg-8" style="background:gainsboro;border:none" id="searchForm" >
                <div class="input-group mb-1">
                    <input type="text" class="form-control" name='search' placeholder="search..." aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            <form method='POST' action="{{ url_for('users.filter') }}" class="col-lg-8 container" style="background:gainsboro;border:none">
                <small>Filter by</small>
                <select class="mb-1 text-muted" name='role'>
                    <option>all</option>
                    <option value='expert'>Expert</option>
                    <option value='recruiter'>Recruiter</option>
                    <option value='admin'>Admin</option>
                </select>
                <input type='submit' class='btn-success border ms-1' name='filter' value='Go'>
            </form>
            <div class="d-flex justify-content-end">
                <a href="{{ url_for('users.add') }}" class="btn-secondary btn">
                    <small>add user</small>
                   <i class="fa fa-plus-circle text-white" aria-hidden="true" style='font-size:20px;'></i>
               </a>
            </div>
           
        </div>
        <table class="table table-striped bg-white">
            <thead class="bg-success text-white">
            <tr>
                <th>USERNAME</th>
                <th>EMAIL ADDRESS</th>
                <th>RECRUITER</th>
                <th>EXPERT</th>
                <th>ADMIN</th>
                <th>DELETE</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
            <tr>
                <td>
                    <input type='checkbox' class="ms-1" value='{{ user.id }}'>
                    <a href="#" class=" text-success">{{ user.username | title}}</a>
                </td>
                <td>
                    <a href="#" class="nav-link text-success">{{ user.email | title}}</a>
                </td>
                <td>
                    {% if user.is_recruiter %}
                    <i class="fa fa-check text-success" style="font-size:17px"></i>
                    {% else %}
                    <i class="fa fa-close text-danger" style="font-size:17px"></i>
                    {% endif %}
                </td>
                <td>
                    {% if user.is_specialist %}
                    <i class="fa fa-check text-success" style="font-size:17px"></i>
                    {% else %}
                    <i class="fa fa-close text-danger" style="font-size:17px"></i>
                    {% endif %}
                </td>
                <td>
                    {% if user.is_admin %}
                    <i class="fa fa-check text-success" style="font-size:17px"></i>
                    {% else %}
                    <i class="fa fa-close text-danger" style="font-size:17px"></i>
                    {% endif %}
                </td>
                <td style="text-align:center">
                    <a href="{{ url_for('users.delete', id=user.id) }}">
                       <i class="fa fa-trash text-warning" aria-hidden="true" style='font-size:20px'></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
            <tr class='bg-light'>
                <td colspan='6'><small class="ms-1">{{ count }} users</small></td>
            </tr>
            </tbody>
        </table>
    {% else %}
        <div class="container">
           <h2>No users into the database</h2>
        </div>
    {% endif %}
   </div>
{% endblock %}