interviewapp/interviews/models.py
from datetime import datetime
from interviewapp import db
from interviewapp.questions.models import Question
from interviewapp.users.models import User


question_association_table = db.Table(
    "question_association",
    db.metadata,
    db.Column("question_id", db.ForeignKey("question.id")),
    db.Column("interview_id", db.ForeignKey("interview.id")),
)

association_table = db.Table(
    "association",
    db.metadata,
    db.Column("interview_id", db.ForeignKey("interview.id")),
    db.Column("user_id", db.ForeignKey("user.id")),
)

class Interview(db.Model):
    __tablename__ = "interview"
    __table_args__ = {"extend_existing": True}

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(30),nullable=False)
    candidate_name = db.Column(db.String(80))
    interview_id = db.Column(db.String(11), unique=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    users = db.relationship("User", secondary=association_table)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    date = db.Column(db.DateTime)
    final_score = db.Column(db.Integer)
    questions = db.relationship("Question", secondary=question_association_table)
    rates = db.relationship("Rate", backref="rate", lazy=True)
  

    def __repr__(self):
        return "{0} {1}".format(self.title, self.created_at)

interviewapp/interviews/forms.py
from flask_wtf import FlaskForm 
from wtforms import (
     SelectField, 
     SelectMultipleField, 
     DateField, StringField,
     SubmitField, 
     SearchField)
from wtforms.validators import DataRequired, Length


from interviewapp.interviews.models import Interview
from interviewapp.questions.models import Question
from interviewapp.users.models import User
from interviewapp.topics.models import Topic

from interviewapp import script
from interviewapp import db 
from flask_login import current_user


class AddInterviewForm(FlaskForm):

    candidate_name = StringField(
        "Candidate name", validators=[Length(min=5, max=60), DataRequired()]
    )
    title = StringField("Title", validators=[Length(min=5, max=60), DataRequired()])
    user = SelectMultipleField("Experts", choices=[], validate_choice=False)
    date = DateField("Interview date")
    submit = SubmitField("Submit")

    def save(self, user_id):
        title = self.title.data
        name = self.candidate_name.data
        date = self.date.data
        users = self.user.data
        code = script.get_unique_code()
        interview = Interview(
            title=title,
            candidate_name=name,
            user_id=user_id,
            date=date,
            interview_id=code,
        )
        for username in users:
            user = User.query.filter_by(username=username).first()
            interview.users.append(user)

    
        return interview

class SearchForm(FlaskForm):
    search = SearchField("Search", validators=[DataRequired()])

interviewapp/interviews/views.py
from flask import (
    Blueprint, 
    flash, redirect, 
    render_template, 
    url_for, request, json, jsonify)

from sqlalchemy import desc
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy import exc
from flask_login import login_required, current_user
from interviewapp import db
from .models import Interview
from interviewapp.interviews.forms import AddInterviewForm
from interviewapp import script

from interviewapp.users.models import User
from interviewapp.topics.models import Topic
from interviewapp.questions.models import Question
from interviewapp.rates.models import Rate

from interviewapp import script


interviews = Blueprint('interviews', __name__, template_folder='templates/interviews')

@interviews.route("/", methods=["GET", "POST"])
@login_required
def home():
    page_title = "Home"
    form = AddInterviewForm()
    form.user.choices = User.query.filter_by(is_specialist=True).all()
    topics = Topic.query.all()
    interviews = Interview.query.order_by(desc(Interview.created_at))[:9]
    questions = Question.query.all()
    if request.method == 'POST':
        if form.validate_on_submit():
            current_user_id = current_user.id
            new_interview = form.save(current_user_id)
            questions = request.form.getlist('question')
            for id in questions:
                q = Question.query.filter_by(id=id).first()
                new_interview.questions.append(q)
            try:
                db.session.add(new_interview)
                db.session.commit()
                flash("Interview successfully added", "success")
                return redirect(url_for("interviews.listing"))
            except exc.SQLAlchemyError:
                flash("something went wrong wen creating interview", "success")
        else:
            flash("Invalid data submited",'danger')


    if current_user.is_specialist:
        return redirect(url_for('interviews.expert_interview_list'))
    return render_template(
        "base.html",
        page_title=page_title,
        form=form,
        interviews=interviews,
        topics=topics,
        questions=questions,
    )



@interviews.route("/<id>/detail/", methods=["POST", "GET"])
@login_required
def detail(id):
    # get interview object by id
    interview = Interview.query.filter_by(id=id).first()
    page_title = "{0} detail".format(interview.title)
    # send json data if header accept json
    if request.is_json:
        json_data = json.dumps(interview)
        return jsonify({"interview": json_data})

    # render html data
    return render_template(
        "interviews/interview_detail.html", 
        interview=interview,page_title=page_title)
    
@interviews.route("/listing/expert",methods=['POST','GET'])
def expert_interview_list():
    page_title = 'interviews'
    current_user_name = current_user.username
    interviews = Interview.query
    interview_list = []
    for interview in interviews:
        for username in script.get_username_list(interview.users):
            if current_user_name == username:
                interview_list.append(interview)

    print(interview_list)
    return render_template('interviews/interview_list.html', page_title=page_title, interviews=interview_list)


@interviews.route("/listing/", methods=['POST','GET'])
@login_required
def listing():

    if current_user.is_specialist:
        return redirect(url_for('interviews.expert_interview_list'))

    page_title = "Interviews"
    interviews = None
    if current_user.is_admin:
        interviews = Interview.query.order_by(desc(Interview.created_at))[:9]
    else:
    # get interviews and ordering by create date LIMIT 9
        interviews = Interview.query.filter_by(user_id=current_user.id).all()
    return render_template(
        'interviews/interview_list.html', 
        page_title=page_title, 
        interviews=interviews
        )


@interviews.route("/search/", methods=['POST', 'GET'])
@login_required
def search():
    # request send using post method
    if request.method == 'POST':
        interviews_data = Interview.query
        # query enter by user using search field
        query = request.form.get('search')
        # if query is empty
        if not query:
            # send flash message of not found 
            flash("warning: empty query was sent",'warning')
            # redirect user to interview list page
            return redirect(url_for('interviews.listing'))
        
        # if query is not empty
        page_title = "{0} interviews".format(query)
        # filter interviews using the query
        matching = interviews_data.filter(Interview.title.like("%" + query + "%")).all()
        # if query word not found in database
        if matching == None:
            # send flash message to interview list
            flash('{0} does not match any interview'.format(query),'info')
            return redirect(url_for('interviews.listing'))
    
    # if GET request is sent
    return render_template(
        'interviews/search_result.html', 
        page_title=page_title, 
        interviews=matching,
        query = query
    )

#delete route is used for deleting interview
@interviews.route("/<id>/delete/", methods=['POST','GET'])
@login_required
def delete(id):
    # get interview to be deleted using id
    interview = Interview.query.filter_by(id=id).first()
    # set the page title 
    page_title = "Delete | {0} ".format(interview.title)
    # if request method is POST
    if request.method == "POST":
        # get interview id send though POST method using hidden field 
        id = request.form.get("id")
        # get interview from database by id
        interview = Interview.query.filter_by(id=id).first()
        try:
            # delete interview from database
            db.session.delete(interview)
            # save changes done in database
            db.session.commit()
            # send flash message to interviews list page
            flash("{0} successfully deleted".format(interview.title), 'success')
            return redirect(url_for('interviews.listing'))
        except SQLAlchemyError as e:
            # notify user that interview could not be deleted
            flash("{0} could not be deleted".format(interview),'warning')
            # redirect user to interview list page
            return redirect(url_for('interviews.listing'))

    # if request method is GET
    return render_template(
        "interviews/interview_delete.html",
         page_title=page_title,
         interview=interview
    )
   

@interviews.route("/<id>/add/question", methods=["POST","GET"])
@login_required
def interview_add_question(id):
    id = id
    topics = Topic.query.all()
    interview = Interview.query.filter_by(id=id).first()
    page_title = "Question | {0}".format(interview.title)
    if request.method == 'POST':
        interview_id = request.form.get('interview_id')
        interview = Interview.query.filter_by(id=interview_id).first()
        id_list = request.form.getlist('question')
    
        for question_id in id_list:
            q = Question.query.filter_by(id=question_id).first()
            interview.questions.append(q)
        db.session.commit()
        
        flash("Question successfully added",'success')
        return redirect(url_for("interview_detail", id=id))

    return render_template(
        "interviews/add_question.html",
        id=id,
        page_title=page_title, 
        topics=topics
        )


@interviews.route("/<inter>/question/<quest>/rate",methods=["POST","GET"])
@login_required
def interview_rate_question(inter, quest):
    # get interview whose question to be rated
    interview_object = Interview.query.filter_by(id=inter).first()

    quest_id = quest
    inter_id = inter
    # get question to be rated
    question_object  = Question.query.filter_by(id=quest).first()

    if request.method == 'POST':
        # user sends an empty field 
        if not request.form.get("username"):
            flash("Evaluator username is required",'danger')
            return redirect(url_for("interview_rate_question",inter=inter, quest=quest))
        else:
            username = request.form.get('username')
            # get user username 
            usernames = script.get_username_list(interview_object.users)
            # if the username matches any evaluator name
            if username in usernames:
                flash("{0} username matches".format(username), 'success')
                return redirect(url_for('rate_question',quest=quest_id, inter=inter_id))
            
            # username not found 
            else:
                flash("Evaluator no found", 'danger')
                return redirect(url_for("interview_rate_question",inter=inter, quest=quest))
            
    return render_template(
        "rate_auth.html",
        question = question_object,
        interview = interview_object
    )
    

@interviews.route("/<id>/rate/",methods=["POST", "GET"])
@login_required
def rate_question(id):
    interview = Interview.query.filter_by(id=id).first()
    if request.method == 'POST':
        rate_value = request.form.get('rate')
        user_id = request.form.get("user_id")
        if not rate_value or user_id == 'None':
            flash("Rate and evaluator are required", 'danger')
        else:
            quest_id = request.form.get('question_id')
            rate = Rate(
                    user_id=user_id, 
                    question_id=quest_id, 
                    value=rate_value,
                    interview_id=interview.id
                )
            try:
                db.session.add(rate)
                db.session.commit()
                flash("successully rated",'success')
            except exc.SQLAlchemyError as e:
                # log the error
                flash("something went wrong when rating ",'danger')

    return redirect(url_for('interviews.detail',id=interview.id))
    

interviewapp/templates/interviews/add_evaluator.html
{% extends 'base.html' %}
{% block content %}
<div class="container col-md-6">
    <form method="POST">
        <input type='hidden' value='{{ id }}' name="interview_id" id="interview_id" />
        <h2>Add evaluator</h2>
        {{ form.hidden_tag() }}
        {{ form.evaluators.label(class="form-control-label")}}
        {% if form.evaluators.error %}
         {{ form.evaluators(class="is-invalid ")}}
         <div class="invalid-feedback">
             {% for error in form.evaluators.errors %}
               <small class="text-danger">{{ error }}</small>
             {% endfor %}
         </div>
        {% else %}
          {{ form.evaluators(class="form-control")}}
        {% endif %}
        <div class="d-flex justify-content-end pt-3">
            {{ form.submit(class="btn btn-success")}}
            <a href="{{ url_for('interviews.detail', id=id) }}" class="btn btn-secondary ms-2">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

interviewapp/templates/interviews/add_question.html
{% extends 'base.html' %}
{% block content %}
<div class="container col-md-6">
    <form method="POST">
        <h2>Add question</h2>
        <input type='hidden' value='{{ id }}' id="interview_id" name="interview_id">
        <div class="form-group mb-3">
            <label class="form-control-label">Topic</label>
            <select name='topic' class="form-control" placeholder="Topic" id="topic">
                {% for topic in topics %}
                  <option value="{{topic.id}}">{{topic.content}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mb-3">
            <label class="form-control-label">Question</label>
            <select name='question' class="form-control" placeholder="question" id="question" multiple required>
                {% for question in questions %}
                  <option value="{{question.id}}">{{question.content}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="d-flex justify-content-end">
            <input type="submit" class="btn btn-success" value="Submit">
            <a href="{{ url_for('interviews.detail', id=id) }}" class="btn btn-secondary ms-2">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

interviewapp/templates/interviews/interview_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="container bg-white">
    <p>Do your really want to delete {{ interview.title }} ? </p>
    <form method="POST" class="col-md-3">
        <a href="{{ url_for('interviews.detail', id=interview.id) }}" class="btn btn-secondary btn-sm">Cancel</a>
        <input type='hidden' value='{{ interview.id }}' id='id' name='id'>
        <input type="submit" class="btn btn-danger btn-sm ms-1" value="delete">
    </form>
</div>
{% endblock %}

interviewapp/templates/interviews/interview_detail.html
{% extends 'base.html' %}
{% block content %}
<style>
    p{font-size:18px}
</style>
<div class="container">
  <div class=" col-md-10">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
    <div class="d-flex justify-content-end pb-2">
        <a href="{{ url_for('interviews.listing') }}" class="btn btn-success">Interviews</a>
        <a href="#" class="btn btn-primary ms-2">Edit</a>
        <a href="{{ url_for('interviews.delete', id=interview.id) }}" class="btn btn-danger ms-2">Detele</a>
    </div>
    <div class="bg-white container pt-3">
      <h2>{{interview.title | title}}</h2>
      <p class="text-muted mt-3">Code :  <span class="text-dark">{{ interview.interview_id}}<span></p>
      <p class="text-muted mt-3">Evaluator Name:
          {% if interview.users %}
            {% for user in interview.users %}
               <span class="text-dark ms-2">{{user.username}}</span>,
            {% endfor %}
          {% else %}
            <a href="{{ url_for('interviews.interview_add_evaluator', id=interview.id) }}" class="btn btn-success btn-sm ms-3">Add evaluator</a>
          {% endif %}
      </p>
      <p class="text-muted mt-3">Candidate name : <span class="text-dark">{{interview.candidate_name | title}}</span></p>
    </div>
    <div class="bg-white container pb-2 pt-2 mt-3">
        <p class="text-muted">Created  : <span class="text-dark">{{ interview.created_at.strftime("%Y-%m-%d")}}<span></p>
        <p class="text-muted">Created by : </p>
         {% if interview.date == None %}
          <p class="text-muted">Schedule on : <a href="#" class="text-dark">No scheduled date</a></p>
         {% else %}
          <p class="text-muted">Schedule on : {{ interview.date.strftime("%Y-%m-%d")}}</p>
         {% endif %}
         <p class="text-muted">Final score : 
             {% if interview.final_score %} 
             <span>{{ interview.final_score }}</span>
             {% else %}
             <span class='text-success'> No final score yet</span>
             {% endif %}
        </p>
    </div>
    <div class="bg-white container mt-3 pt-3 pb-2">
        {% if interview.questions %}
            {% for q in interview.questions %}
            <div class="card mb-3 border-secondary">
                <div class="card-header bg-secondary border border-secondary">
                  <span class="text-white">Question</span>
                </div>

                <div class="card-body">
                  <h6 class="card-title mb-3">{{ q.content | title }}</h6>
                  <h6 class="text-muted">Answer : <span class="text-dark">{{ q.expected_answer | title }}</span></h6>
                  <p><span class="">Max score</span> : {{q.max_score }}</p>

                  <form method="POST" action="{{ url_for('interviews.rate_question',id=interview.id) }}" class="col-md-3 ps-0">
                    <input type='hidden' value='{{ q.id }}' name='question_id' id='question_id'>
                    <select class="form-control mb-2" id="user_id" name="user_id">
                      <option class="text-muted" value="None">Select evaluator</option>
                      {% for user in interview.users %}
                        <option value="{{user.id}}">{{ user.username }}</option>
                      {% endfor %}
                    </select>
                    <input type="number" id="rate" name="rate" class="form-control" placeholder="Your rate here" max=5 min=2>
                    <div class="pt-3">
                        <input type='submit' class="btn btn-success" value="Rate now">
                    </div>
                  </form>

                </div>
            </div>
            {% endfor %}
        {% else %}
            <p>No question for this interview <a href="{{ url_for('interviews.interview_add_question', id=interview.id) }}" class="btn btn-success btn-sm"> add here</a></p>
        {% endif%}
    </div>
</div>
{% endblock %}

interviewapp/templates/interviews/interview_list.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
        {% endif %}
    {% endwith %}
</div>
<div class="mb-3 container justify-content-center d-flex">
    <form method='POST' action="{{ url_for('interviews.search') }}" style="background:gainsboro;border:none" id="searchForm">
        <input type="text" class="pb-1" placeholder="Search.." name="search" id="InterviewSearchField">
        <button type='submit' class="btn btn-success btn-sm" id='BtnSearchInterview'><i class="fa fa-search"></i></button>
    </form>
    {% if current_user.is_recruiter %}
    <a href="{{ url_for('interviews.home') }}"><i class="fa fa-plus-circle text-success" aria-hidden="true" style='font-size:30px'></i></a>
    {% endif %}
</div>
<div class="container">
    <table class="table table-striped bg-white" id="interview-table">
        <thead class="bg-success text-white">
        <tr>
            <th><input type='checkbox'></th>
            <th>TITLE</th>
            <th>CANDIDATE NAME</th>
            <th>INTERVIEW DATE</th>
        </tr>
        </thead>
        <tbody>
        {% if not interviews %}
        <tr>
          <td colspan='5'><p>There is not interview for you</p></td>
        </tr>
        {% else %}
            {% for interview in interviews %}
            <tr>
                <td><input type='checkbox' class=''></td>
                <td><a href="{{ url_for('interviews.detail', id=interview.id) }}" class="nav-link text-success">{{ interview.title | title}}</a></td>
                <td>{{ interview.candidate_name }}</td>
                <td>{{ interview.date.strftime("%m - %d - %Y") }}</td>
            </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

interviewapp/templates/interviews/search_result.html
{% extends 'base.html' %}
{% block content %}
<div class="mb-3 container justify-content-center d-flex">
    <form method='POST' action="" style="background:gainsboro;border:none" id="searchForm">
        <input type="text" value='{{ query }}' class="pb-1" placeholder="Search.." name="search" id="InterviewSearchField">
        <button type='submit' class="btn btn-success btn-sm" id='BtnSearchInterview'><i class="fa fa-search"></i></button>
    </form>
    <a href="{{ url_for('home') }}"><i class="fa fa-plus-circle text-success" aria-hidden="true" style='font-size:30px'></i></a>
</div>
<div class="container">
    <table class="table table-striped bg-white" id="interview-table">
        <thead class="bg-success text-white">
        <tr>
            <th>Title</th>
            <th>Candidate name</th>
            <th>Interview date</th>
        </tr>
        </thead>
        <tbody>
        {% for interview in interviews %}
        <tr>
            <td><a href="{{ url_for('interviews.detail', id=interview.id) }}" class="nav-link text-success">{{ interview.title | title}}</a></td>
            <td>{{ interview.candidate_name }}</td>
            <td>{{ interview.date.strftime("%m - %d - %Y") }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}